@baseUrlLocal = http://localhost:3333

# @name setUser
POST {{baseUrlLocal}}/users
Content-Type: application/json

{
  "name": "Pedro Dias",
  "email": "pedropd@acme.com",
  "password": "123456"
}
###

# @name validatePassword
POST {{baseUrlLocal}}/sessions/password
Content-Type: application/json

{
  "name": "Pedro Dias",
  "email": "pedropd@acme.com",
  "password": "123456"
}