@baseUrlLocal = http://localhost:3333
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMGY3NDhiNS1kODFiLTQ5MDktYjRkZi0zOTk5YTM5YTA1NmQiLCJpYXQiOjE3MTU5NzU1NjQsImV4cCI6MTcxNjU4MDM2NH0.tjP4Wa8S3G0P2vzuZTT6kf6kY5eZAYKTc9QgVIFlH3A

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYjgwNDkwYy0yMzA3LTQ4MWItOTRjZC01YTM0NmQzMDQ3NDQiLCJpYXQiOjE3MjE1Mjk4MjcsImV4cCI6MTcyMjEzNDYyN30.MTsPMdleBI7LIXorBDGlR3F8Oj5MvlNLV6ll37opBig

# @name setUser
POST {{baseUrlLocal}}/users
Content-Type: application/json

{
  "name": "Pedro Dias",
  "email": "pedropd@acme.com",
  "password": "123456"
}

###

# @name validatePassword
POST {{baseUrlLocal}}/sessions/password
Content-Type: application/json

{
  "name": "Pedro Dias",
  "email": "pedropd@acme.com",
  "password": "654321"
}

###

# @name getValidatedUser
GET {{baseUrlLocal}}/profile
Content-Type: application/json
Authorization: Bearer {{userToken}}

###

# @name getOrgProjects
GET {{baseUrlLocal}}/organizations/acme-admin/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name deleteOrg

DELETE  {{baseUrlLocal}}/organizations/fddf
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name getOrg
GET {{baseUrlLocal}}/organizations
Content-Type: application/json
Authorization: Bearer {{authToken}}